logging:
  level:
    com:
      dhiman:
        ai:
          bot: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

app:
  properties:
    setup-vector-store: false
    text-source: text-source.txt

