logging:
  level:
    com:
      dhiman:
        ai:
          bot: DEBUG
spring:
  ai:
    vectorstore:
      pinecone:
        apiKey: ${PINECONE_API_KEY}
        environment: ${PINECONE_ENV}
        projectId: ${PINECONE_PROJECT_ID}
        index-name: ${PINECONE_INDEX_NAME}
app:
  properties:
    text-source: text-source.txt

