logging:
  level:
    com:
      dhiman:
        ai:
          bot: INFO
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${PGUSER}
    password: ${PGPASSWORD}

app:
  properties:
    setup-vector-store: false
    text-source: text-source.txt

