name: Build App and  Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '21'
    - run: mvn clean install -Dmaven.test.skip=true
    

