name: Build App and  Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v4
    - name: maven-build 
    - uses: actions/setup-java@v4
      with:
         distribution: 'temurin'
         java-version: '21'
    - run: mvn clean install -Dmaven.test.skip=true
    

